version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  tests:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m unittest
          name: Unit tests
  publish:
    executor: python/default
    steps: 
      - add_ssh_keys:
        fingerprints:
          - b6:48:80:38:11:f7:f6:31:25:4d:04:41:37:d2:a5:41
       - git config user.email "anomaly.the@gmail.com"
       - git config user.name "Gyanendra Mishra"
       - python ./circleci/update-tags.py

workflows:
  version: 2
  main:
    jobs:
      - tests
      - publish:
          filters:
            branches:
              only:
                -   master

