DEFAULT_PAGE_SIZE = 15


# CATEGORIES OF RESULTS
QUESTION = "question"
ISSUE = "issue"
CODE = "code"
REPO = "repository"
MESSAGE = "message"


# Trello
CARDS = "cards"
BOARDS = "boards"
ORGANIZATIONS = "organizations"
MEMBERS = "members"


GITHUB_QUALIFIERS = {
    "in:file": True,
    "in:path": True,
    "in:name": True,
    "in:description": True,
    "in:readme": True,
    "user": True,
    "org": True,
    "repo": True,
    "path": True,
    "size": True,
    "filename": True,
    "extension": True,
    "followers": True,
    "forks": True,
    "created": True,
    "pushed": True,
    "language": True,
    "topic": True,
    "topics": True,
    "license": True,
    "is:public": True,
    "is:private": True,
    "mirror:true": True,
    "mirror:false": True,
    "good-first-issues": True,
    "help-wanted-issues": True,
    "is:curated": True,
    "is:featured": True,
    "is:not-curated": True,
    "is:not-featured": True,
    "repositories": True,
    "author": True,
    "committer": True,
    "author-name": True,
    "committer-name": True,
    "author-email": True,
    "committer-email": True,
    "author-date": True,
    "committer-date": True,
    "merge:true": True,
    "merge:false": True,
    "hash": True,
    "parent": True,
    "tree": True,
    "type:pr": True,
    "type:issue": True,
    "is:pr": True,
    "is:issue": True,
    "in:title": True,
    "in:body": True,
    "in:comments": True,
    "state:open": True,
    "state:closed": True,
    "is:open": True,
    "is:closed": True,
    "assignee": True,
    "mentions": True,
    "team": True,
    "commenter": True,
    "involves": True,
    "linked:pr": True,
    "linked:issue": True,
    "-linked:pr": True,
    "-linked:issue": True,
    "label:LABEL": True,
    "milestone": True,
    "project": True,
    "status:pending": True,
    "status:success": True,
    "status:failure": True,
    "head": True,
    "base": True,
    "comments": True,
    "interactions": True,
    "reactions": True,
    "draft:true": True,
    "draft:false": True,
    "review:none": True,
    "review:required": True,
    "review:approved": True,
    "review:changes_requested": True,
    "reviewed-by": True,
    "review-requested": True,
    "team-review-requested": True,
    "updated": True,
    "closed": True,
    "merged": True,
    "is:merged": True,
    "is:unmerged": True,
    "archived:true": True,
    "archived:false": True,
    "is:locked": True,
    "is:unlocked": True,
    "no:label": True,
    "no:milestone": True,
    "no:assignee": True,
    "no:project": True,
    "type:user": True,
    "type:org": True,
    "in:login": True,
    "fullname:": True,
    "in:email": True,
    "repos": True,
    "location": True,
    "fork:only": True,
    "fork:true": True,
}
